// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scheduler.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

type ClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLeader      bool                   `protobuf:"varint,1,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,4,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	HaEnabled     bool                   `protobuf:"varint,5,opt,name=ha_enabled,json=haEnabled,proto3" json:"ha_enabled,omitempty"`
	Members       []*ClusterMember       `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterStatusResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *ClusterStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClusterStatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *ClusterStatusResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *ClusterStatusResponse) GetHaEnabled() bool {
	if x != nil {
		return x.HaEnabled
	}
	return false
}

func (x *ClusterStatusResponse) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ClusterMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Leader        bool                   `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Suffrage      string                 `protobuf:"bytes,4,opt,name=suffrage,proto3" json:"suffrage,omitempty"` // Voter or Nonvoter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMember) Reset() {
	*x = ClusterMember{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMember) ProtoMessage() {}

func (x *ClusterMember) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMember.ProtoReflect.Descriptor instead.
func (*ClusterMember) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterMember) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClusterMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClusterMember) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *ClusterMember) GetSuffrage() string {
	if x != nil {
		return x.Suffrage
	}
	return ""
}

type CordonNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Cordon        bool                   `protobuf:"varint,2,opt,name=cordon,proto3" json:"cordon,omitempty"` // true to cordon, false to return the node to service
	Drain         bool                   `protobuf:"varint,3,opt,name=drain,proto3" json:"drain,omitempty"`   // also cancel the jobs currently running on the node
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`  // recorded and shown in `tasch nodes`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonNodeRequest) Reset() {
	*x = CordonNodeRequest{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonNodeRequest) ProtoMessage() {}

func (x *CordonNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonNodeRequest.ProtoReflect.Descriptor instead.
func (*CordonNodeRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *CordonNodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CordonNodeRequest) GetCordon() bool {
	if x != nil {
		return x.Cordon
	}
	return false
}

func (x *CordonNodeRequest) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

func (x *CordonNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CordonNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Cordoned      bool                   `protobuf:"varint,2,opt,name=cordoned,proto3" json:"cordoned,omitempty"`
	JobsCancelled int32                  `protobuf:"varint,3,opt,name=jobs_cancelled,json=jobsCancelled,proto3" json:"jobs_cancelled,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonNodeResponse) Reset() {
	*x = CordonNodeResponse{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonNodeResponse) ProtoMessage() {}

func (x *CordonNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonNodeResponse.ProtoReflect.Descriptor instead.
func (*CordonNodeResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *CordonNodeResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CordonNodeResponse) GetCordoned() bool {
	if x != nil {
		return x.Cordoned
	}
	return false
}

func (x *CordonNodeResponse) GetJobsCancelled() int32 {
	if x != nil {
		return x.JobsCancelled
	}
	return 0
}

func (x *CordonNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AcknowledgeStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerNode    string                 `protobuf:"bytes,2,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Attempt       int64                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeStartRequest) Reset() {
	*x = AcknowledgeStartRequest{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeStartRequest) ProtoMessage() {}

func (x *AcknowledgeStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeStartRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeStartRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *AcknowledgeStartRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AcknowledgeStartRequest) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *AcknowledgeStartRequest) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type AcknowledgeStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeStartResponse) Reset() {
	*x = AcknowledgeStartResponse{}
	mi := &file_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeStartResponse) ProtoMessage() {}

func (x *AcknowledgeStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeStartResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeStartResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *AcknowledgeStartResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type WatchDispatchRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Jobs this worker is currently executing, sent every time the stream is established.
	//
	// A master restart used to mark every RUNNING job FAILED without contacting anyone. The
	// workers kept executing them, holding CPU and GPU that the new master's empty accounting
	// believed were free, so it immediately oversubscribed those nodes — and when a job finally
	// finished, its result was discarded because the master no longer had the job. Reporting what
	// is actually running lets the master adopt those jobs instead of guessing.
	RunningJobs   []*RunningJob `protobuf:"bytes,2,rep,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDispatchRequest) Reset() {
	*x = WatchDispatchRequest{}
	mi := &file_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDispatchRequest) ProtoMessage() {}

func (x *WatchDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDispatchRequest.ProtoReflect.Descriptor instead.
func (*WatchDispatchRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *WatchDispatchRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *WatchDispatchRequest) GetRunningJobs() []*RunningJob {
	if x != nil {
		return x.RunningJobs
	}
	return nil
}

// RunningJob identifies work a worker is executing, so the master can reconcile against it.
type RunningJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Attempt       int64                  `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"` // Fencing token from the dispatch that started it
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningJob) Reset() {
	*x = RunningJob{}
	mi := &file_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningJob) ProtoMessage() {}

func (x *RunningJob) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningJob.ProtoReflect.Descriptor instead.
func (*RunningJob) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *RunningJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunningJob) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RunningJob) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type DispatchMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	WalltimeSeconds int32                  `protobuf:"varint,3,opt,name=walltime_seconds,json=walltimeSeconds,proto3" json:"walltime_seconds,omitempty"`
	Action          string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // "execute" or "cancel"
	EnvVars         map[string]string      `protobuf:"bytes,5,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Attempt         int64                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"` // Fencing token, echoed back in ReportResult
	// Resource reservations, so the worker can enforce them rather than leaving them as
	// bookkeeping on the master. A job that reserved one core could previously consume the whole
	// machine, because nothing on the worker ever applied a limit.
	CpusRequired     int32 `protobuf:"varint,7,opt,name=cpus_required,json=cpusRequired,proto3" json:"cpus_required,omitempty"`
	MemoryRequiredMb int32 `protobuf:"varint,8,opt,name=memory_required_mb,json=memoryRequiredMb,proto3" json:"memory_required_mb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DispatchMessage) Reset() {
	*x = DispatchMessage{}
	mi := &file_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchMessage) ProtoMessage() {}

func (x *DispatchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchMessage.ProtoReflect.Descriptor instead.
func (*DispatchMessage) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *DispatchMessage) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchMessage) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DispatchMessage) GetWalltimeSeconds() int32 {
	if x != nil {
		return x.WalltimeSeconds
	}
	return 0
}

func (x *DispatchMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DispatchMessage) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *DispatchMessage) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DispatchMessage) GetCpusRequired() int32 {
	if x != nil {
		return x.CpusRequired
	}
	return 0
}

func (x *DispatchMessage) GetMemoryRequiredMb() int32 {
	if x != nil {
		return x.MemoryRequiredMb
	}
	return 0
}

type SubmitJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CelRequirement  string                 `protobuf:"bytes,1,opt,name=cel_requirement,json=celRequirement,proto3" json:"cel_requirement,omitempty"`
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Priority        int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                                                                       // Lower = higher priority (default: 10)
	User            string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                                                                                // For fairshare tracking
	WalltimeSeconds int32                  `protobuf:"varint,5,opt,name=walltime_seconds,json=walltimeSeconds,proto3" json:"walltime_seconds,omitempty"`                                                  // Max execution time (0 = no limit)
	GpusRequired    int32                  `protobuf:"varint,6,opt,name=gpus_required,json=gpusRequired,proto3" json:"gpus_required,omitempty"`                                                           // Number of GPUs needed (0 = none)
	EnvVars         map[string]string      `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom environment variables
	// Explicit resource reservations. Distinct from cel_requirement, which filters which nodes
	// are eligible: "ad.cpu_cores >= 4" asks for a node with at least 4 cores, it does not
	// reserve 4 of them. These were previously scraped out of the CEL string with a regex, so
	// any expression the regex did not literally match reserved nothing and the node was freely
	// oversubscribed. 0 falls back to that regex for backward compatibility.
	CpusRequired     int32 `protobuf:"varint,8,opt,name=cpus_required,json=cpusRequired,proto3" json:"cpus_required,omitempty"`               // CPU cores to reserve (0 = infer from cel_requirement)
	MemoryRequiredMb int32 `protobuf:"varint,9,opt,name=memory_required_mb,json=memoryRequiredMb,proto3" json:"memory_required_mb,omitempty"` // Memory to reserve in MB (0 = infer)
	// Jobs that must finish before this one starts. Each must already exist, which is what makes
	// a dependency cycle impossible to express rather than something to detect.
	DependsOn []string `protobuf:"bytes,10,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// Which outcome releases the job: afterok (default), afterany, afternotok.
	DependencyMode string `protobuf:"bytes,11,opt,name=dependency_mode,json=dependencyMode,proto3" json:"dependency_mode,omitempty"`
	// Array specification: "1-100", "1-100%5" to cap concurrency at 5, or an explicit list like
	// "1,4,7". Submitting once and letting the scheduler expand it is what lets it throttle the
	// tasks; a shell loop of submissions cannot be throttled by anything but the shell.
	Array string `protobuf:"bytes,12,opt,name=array,proto3" json:"array,omitempty"`
	// Which pool of nodes to run on, and which account to charge. Both are optional: with no
	// partitions or accounts configured they are ignored, and with them configured a job that
	// names neither takes the default partition and the submitter's first account.
	Partition     string `protobuf:"bytes,13,opt,name=partition,proto3" json:"partition,omitempty"`
	Account       string `protobuf:"bytes,14,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitJobRequest) GetCelRequirement() string {
	if x != nil {
		return x.CelRequirement
	}
	return ""
}

func (x *SubmitJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SubmitJobRequest) GetWalltimeSeconds() int32 {
	if x != nil {
		return x.WalltimeSeconds
	}
	return 0
}

func (x *SubmitJobRequest) GetGpusRequired() int32 {
	if x != nil {
		return x.GpusRequired
	}
	return 0
}

func (x *SubmitJobRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *SubmitJobRequest) GetCpusRequired() int32 {
	if x != nil {
		return x.CpusRequired
	}
	return 0
}

func (x *SubmitJobRequest) GetMemoryRequiredMb() int32 {
	if x != nil {
		return x.MemoryRequiredMb
	}
	return 0
}

func (x *SubmitJobRequest) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *SubmitJobRequest) GetDependencyMode() string {
	if x != nil {
		return x.DependencyMode
	}
	return ""
}

func (x *SubmitJobRequest) GetArray() string {
	if x != nil {
		return x.Array
	}
	return ""
}

func (x *SubmitJobRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *SubmitJobRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type SubmitJobResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	JobId  string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// For an array submission: every task's ID, and the array they share. job_id carries the
	// first task, so a client that does not know about arrays still gets something usable.
	JobIds        []string `protobuf:"bytes,3,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	ArrayId       string   `protobuf:"bytes,4,opt,name=array_id,json=arrayId,proto3" json:"array_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitJobResponse) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

func (x *SubmitJobResponse) GetArrayId() string {
	if x != nil {
		return x.ArrayId
	}
	return ""
}

type SubmitDistributedJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CelRequirement  string                 `protobuf:"bytes,1,opt,name=cel_requirement,json=celRequirement,proto3" json:"cel_requirement,omitempty"` // Must match on ALL allocated nodes
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                     // Command template (same on all nodes)
	NumNodes        int32                  `protobuf:"varint,3,opt,name=num_nodes,json=numNodes,proto3" json:"num_nodes,omitempty"`                  // How many nodes to allocate
	GpusPerNode     int32                  `protobuf:"varint,4,opt,name=gpus_per_node,json=gpusPerNode,proto3" json:"gpus_per_node,omitempty"`       // GPUs per node
	Priority        int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	User            string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	WalltimeSeconds int32                  `protobuf:"varint,7,opt,name=walltime_seconds,json=walltimeSeconds,proto3" json:"walltime_seconds,omitempty"`
	MasterPort      int32                  `protobuf:"varint,8,opt,name=master_port,json=masterPort,proto3" json:"master_port,omitempty"`                                                                 // DDP coordination port (default: 29500)
	EnvVars         map[string]string      `protobuf:"bytes,9,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional env vars for all ranks
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitDistributedJobRequest) Reset() {
	*x = SubmitDistributedJobRequest{}
	mi := &file_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDistributedJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDistributedJobRequest) ProtoMessage() {}

func (x *SubmitDistributedJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDistributedJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitDistributedJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitDistributedJobRequest) GetCelRequirement() string {
	if x != nil {
		return x.CelRequirement
	}
	return ""
}

func (x *SubmitDistributedJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SubmitDistributedJobRequest) GetNumNodes() int32 {
	if x != nil {
		return x.NumNodes
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetGpusPerNode() int32 {
	if x != nil {
		return x.GpusPerNode
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SubmitDistributedJobRequest) GetWalltimeSeconds() int32 {
	if x != nil {
		return x.WalltimeSeconds
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetMasterPort() int32 {
	if x != nil {
		return x.MasterPort
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type SubmitDistributedJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	JobIds        []string               `protobuf:"bytes,2,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDistributedJobResponse) Reset() {
	*x = SubmitDistributedJobResponse{}
	mi := &file_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDistributedJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDistributedJobResponse) ProtoMessage() {}

func (x *SubmitDistributedJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDistributedJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitDistributedJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitDistributedJobResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SubmitDistributedJobResponse) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

func (x *SubmitDistributedJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *CancelJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State      string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // QUEUED, RUNNING, COMPLETED, FAILED, CANCELLED
	WorkerNode string                 `protobuf:"bytes,3,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Command    string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Output     string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error      string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	SubmitTime int64                  `protobuf:"varint,7,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	StartTime  int64                  `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime    int64                  `protobuf:"varint,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	GroupId    string                 `protobuf:"bytes,10,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // Empty if not part of a distributed job
	DependsOn  []string               `protobuf:"bytes,11,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	ArrayId    string                 `protobuf:"bytes,12,opt,name=array_id,json=arrayId,proto3" json:"array_id,omitempty"`
	ArrayIndex int32                  `protobuf:"varint,13,opt,name=array_index,json=arrayIndex,proto3" json:"array_index,omitempty"`
	// Why a queued job is not running yet: an unmet dependency, or its array's concurrency cap.
	// Empty when nothing is holding it back.
	BlockedReason string `protobuf:"bytes,14,opt,name=blocked_reason,json=blockedReason,proto3" json:"blocked_reason,omitempty"`
	Partition     string `protobuf:"bytes,15,opt,name=partition,proto3" json:"partition,omitempty"`
	Account       string `protobuf:"bytes,16,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetJobStatusResponse) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *GetJobStatusResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetJobStatusResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GetJobStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetJobStatusResponse) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *GetJobStatusResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetJobStatusResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetJobStatusResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetJobStatusResponse) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *GetJobStatusResponse) GetArrayId() string {
	if x != nil {
		return x.ArrayId
	}
	return ""
}

func (x *GetJobStatusResponse) GetArrayIndex() int32 {
	if x != nil {
		return x.ArrayIndex
	}
	return 0
}

func (x *GetJobStatusResponse) GetBlockedReason() string {
	if x != nil {
		return x.BlockedReason
	}
	return ""
}

func (x *GetJobStatusResponse) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *GetJobStatusResponse) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type LogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	mi := &file_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{18}
}

func (x *LogStreamRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *LogMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogMessage) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WorkerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatusRequest) Reset() {
	*x = WorkerStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusRequest) ProtoMessage() {}

func (x *WorkerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusRequest.ProtoReflect.Descriptor instead.
func (*WorkerStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{20}
}

type WorkerStatusResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	WorkerNodes   map[string]string               `protobuf:"bytes,1,rep,name=worker_nodes,json=workerNodes,proto3" json:"worker_nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // node name -> ClassAd JSON
	NodeState     map[string]*NodeSchedulingState `protobuf:"bytes,2,rep,name=node_state,json=nodeState,proto3" json:"node_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatusResponse) Reset() {
	*x = WorkerStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusResponse) ProtoMessage() {}

func (x *WorkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{21}
}

func (x *WorkerStatusResponse) GetWorkerNodes() map[string]string {
	if x != nil {
		return x.WorkerNodes
	}
	return nil
}

func (x *WorkerStatusResponse) GetNodeState() map[string]*NodeSchedulingState {
	if x != nil {
		return x.NodeState
	}
	return nil
}

// NodeSchedulingState describes why a node is or is not receiving work.
type NodeSchedulingState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cordoned      bool                   `protobuf:"varint,1,opt,name=cordoned,proto3" json:"cordoned,omitempty"`
	CordonReason  string                 `protobuf:"bytes,2,opt,name=cordon_reason,json=cordonReason,proto3" json:"cordon_reason,omitempty"`
	CircuitBroken bool                   `protobuf:"varint,3,opt,name=circuit_broken,json=circuitBroken,proto3" json:"circuit_broken,omitempty"` // temporarily blocked after consecutive failures
	RunningJobs   int32                  `protobuf:"varint,4,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	GpusAllocated int32                  `protobuf:"varint,5,opt,name=gpus_allocated,json=gpusAllocated,proto3" json:"gpus_allocated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSchedulingState) Reset() {
	*x = NodeSchedulingState{}
	mi := &file_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSchedulingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSchedulingState) ProtoMessage() {}

func (x *NodeSchedulingState) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSchedulingState.ProtoReflect.Descriptor instead.
func (*NodeSchedulingState) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *NodeSchedulingState) GetCordoned() bool {
	if x != nil {
		return x.Cordoned
	}
	return false
}

func (x *NodeSchedulingState) GetCordonReason() string {
	if x != nil {
		return x.CordonReason
	}
	return ""
}

func (x *NodeSchedulingState) GetCircuitBroken() bool {
	if x != nil {
		return x.CircuitBroken
	}
	return false
}

func (x *NodeSchedulingState) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *NodeSchedulingState) GetGpusAllocated() int32 {
	if x != nil {
		return x.GpusAllocated
	}
	return 0
}

type ListJobsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StateFilter string                 `protobuf:"bytes,1,opt,name=state_filter,json=stateFilter,proto3" json:"state_filter,omitempty"` // Optional: filter by state
	// Pagination. The response previously carried every job in one message, which on a busy
	// cluster is both an unbounded allocation on the master and a response that can exceed gRPC's
	// receive limit, making the call fail outright rather than return a large result.
	PageSize      int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 0 uses the server default; capped by the server maximum
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // next_page_token from a previous response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_scheduler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{23}
}

func (x *ListJobsRequest) GetStateFilter() string {
	if x != nil {
		return x.StateFilter
	}
	return ""
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty when this is the last page
	TotalMatching int32                  `protobuf:"varint,3,opt,name=total_matching,json=totalMatching,proto3" json:"total_matching,omitempty"`  // jobs matching the filter, across all pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_scheduler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{24}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListJobsResponse) GetTotalMatching() int32 {
	if x != nil {
		return x.TotalMatching
	}
	return 0
}

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Requirement   string                 `protobuf:"bytes,4,opt,name=requirement,proto3" json:"requirement,omitempty"`
	WorkerNode    string                 `protobuf:"bytes,5,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	User          string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	SubmitTime    int64                  `protobuf:"varint,8,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	GroupId       string                 `protobuf:"bytes,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_scheduler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{25}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobInfo) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *JobInfo) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *JobInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *JobInfo) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *JobInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ReportResultRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerNode string                 `protobuf:"bytes,2,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Success    bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output     string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error      string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	StartTime  int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime    int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Dispatch attempt this result belongs to, echoed back from the dispatch payload. The master
	// discards results from a stale attempt: without it, a late report from a previously
	// dispatched worker released the allocation belonging to whichever node is running the job
	// now, and no result could be told apart from a duplicate.
	Attempt       int64 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_scheduler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{26}
}

func (x *ReportResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportResultRequest) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *ReportResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ReportResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportResultRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ReportResultRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ReportResultRequest) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_scheduler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{27}
}

func (x *ReportResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\x02v1\"\x16\n" +
	"\x14ClusterStatusRequest\"\xdd\x01\n" +
	"\x15ClusterStatusResponse\x12\x1b\n" +
	"\tis_leader\x18\x01 \x01(\bR\bisLeader\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x04 \x01(\tR\rleaderAddress\x12\x1d\n" +
	"\n" +
	"ha_enabled\x18\x05 \x01(\bR\thaEnabled\x12+\n" +
	"\amembers\x18\x06 \x03(\v2\x11.v1.ClusterMemberR\amembers\"v\n" +
	"\rClusterMember\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\bR\x06leader\x12\x1a\n" +
	"\bsuffrage\x18\x04 \x01(\tR\bsuffrage\"v\n" +
	"\x11CordonNodeRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x16\n" +
	"\x06cordon\x18\x02 \x01(\bR\x06cordon\x12\x14\n" +
	"\x05drain\x18\x03 \x01(\bR\x05drain\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x8e\x01\n" +
	"\x12CordonNodeResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1a\n" +
	"\bcordoned\x18\x02 \x01(\bR\bcordoned\x12%\n" +
	"\x0ejobs_cancelled\x18\x03 \x01(\x05R\rjobsCancelled\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"k\n" +
	"\x17AcknowledgeStartRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vworker_node\x18\x02 \x01(\tR\n" +
	"workerNode\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x03R\aattempt\">\n" +
	"\x18AcknowledgeStartResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"f\n" +
	"\x14WatchDispatchRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x121\n" +
	"\frunning_jobs\x18\x02 \x03(\v2\x0e.v1.RunningJobR\vrunningJobs\"\\\n" +
	"\n" +
	"RunningJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\x03R\aattempt\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\"\xeb\x02\n" +
	"\x0fDispatchMessage\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12)\n" +
	"\x10walltime_seconds\x18\x03 \x01(\x05R\x0fwalltimeSeconds\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12;\n" +
	"\benv_vars\x18\x05 \x03(\v2 .v1.DispatchMessage.EnvVarsEntryR\aenvVars\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x03R\aattempt\x12#\n" +
	"\rcpus_required\x18\a \x01(\x05R\fcpusRequired\x12,\n" +
	"\x12memory_required_mb\x18\b \x01(\x05R\x10memoryRequiredMb\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x04\n" +
	"\x10SubmitJobRequest\x12'\n" +
	"\x0fcel_requirement\x18\x01 \x01(\tR\x0ecelRequirement\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12)\n" +
	"\x10walltime_seconds\x18\x05 \x01(\x05R\x0fwalltimeSeconds\x12#\n" +
	"\rgpus_required\x18\x06 \x01(\x05R\fgpusRequired\x12<\n" +
	"\benv_vars\x18\a \x03(\v2!.v1.SubmitJobRequest.EnvVarsEntryR\aenvVars\x12#\n" +
	"\rcpus_required\x18\b \x01(\x05R\fcpusRequired\x12,\n" +
	"\x12memory_required_mb\x18\t \x01(\x05R\x10memoryRequiredMb\x12\x1d\n" +
	"\n" +
	"depends_on\x18\n" +
	" \x03(\tR\tdependsOn\x12'\n" +
	"\x0fdependency_mode\x18\v \x01(\tR\x0edependencyMode\x12\x14\n" +
	"\x05array\x18\f \x01(\tR\x05array\x12\x1c\n" +
	"\tpartition\x18\r \x01(\tR\tpartition\x12\x18\n" +
	"\aaccount\x18\x0e \x01(\tR\aaccount\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\ajob_ids\x18\x03 \x03(\tR\x06jobIds\x12\x19\n" +
	"\barray_id\x18\x04 \x01(\tR\aarrayId\"\xa2\x03\n" +
	"\x1bSubmitDistributedJobRequest\x12'\n" +
	"\x0fcel_requirement\x18\x01 \x01(\tR\x0ecelRequirement\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1b\n" +
	"\tnum_nodes\x18\x03 \x01(\x05R\bnumNodes\x12\"\n" +
	"\rgpus_per_node\x18\x04 \x01(\x05R\vgpusPerNode\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12)\n" +
	"\x10walltime_seconds\x18\a \x01(\x05R\x0fwalltimeSeconds\x12\x1f\n" +
	"\vmaster_port\x18\b \x01(\x05R\n" +
	"masterPort\x12G\n" +
	"\benv_vars\x18\t \x03(\v2,.v1.SubmitDistributedJobRequest.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x1cSubmitDistributedJobResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\ajob_ids\x18\x02 \x03(\tR\x06jobIds\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\\\n" +
	"\x11CancelJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xdc\x03\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vworker_node\x18\x03 \x01(\tR\n" +
	"workerNode\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vsubmit_time\x18\a \x01(\x03R\n" +
	"submitTime\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\x03R\aendTime\x12\x19\n" +
	"\bgroup_id\x18\n" +
	" \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"depends_on\x18\v \x03(\tR\tdependsOn\x12\x19\n" +
	"\barray_id\x18\f \x01(\tR\aarrayId\x12\x1f\n" +
	"\varray_index\x18\r \x01(\x05R\n" +
	"arrayIndex\x12%\n" +
	"\x0eblocked_reason\x18\x0e \x01(\tR\rblockedReason\x12\x1c\n" +
	"\tpartition\x18\x0f \x01(\tR\tpartition\x12\x18\n" +
	"\aaccount\x18\x10 \x01(\tR\aaccount\")\n" +
	"\x10LogStreamRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"q\n" +
	"\n" +
	"LogMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\"\x15\n" +
	"\x13WorkerStatusRequest\"\xc3\x02\n" +
	"\x14WorkerStatusResponse\x12L\n" +
	"\fworker_nodes\x18\x01 \x03(\v2).v1.WorkerStatusResponse.WorkerNodesEntryR\vworkerNodes\x12F\n" +
	"\n" +
	"node_state\x18\x02 \x03(\v2'.v1.WorkerStatusResponse.NodeStateEntryR\tnodeState\x1a>\n" +
	"\x10WorkerNodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\x0eNodeStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.v1.NodeSchedulingStateR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x13NodeSchedulingState\x12\x1a\n" +
	"\bcordoned\x18\x01 \x01(\bR\bcordoned\x12#\n" +
	"\rcordon_reason\x18\x02 \x01(\tR\fcordonReason\x12%\n" +
	"\x0ecircuit_broken\x18\x03 \x01(\bR\rcircuitBroken\x12!\n" +
	"\frunning_jobs\x18\x04 \x01(\x05R\vrunningJobs\x12%\n" +
	"\x0egpus_allocated\x18\x05 \x01(\x05R\rgpusAllocated\"p\n" +
	"\x0fListJobsRequest\x12!\n" +
	"\fstate_filter\x18\x01 \x01(\tR\vstateFilter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x82\x01\n" +
	"\x10ListJobsResponse\x12\x1f\n" +
	"\x04jobs\x18\x01 \x03(\v2\v.v1.JobInfoR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12%\n" +
	"\x0etotal_matching\x18\x03 \x01(\x05R\rtotalMatching\"\xff\x01\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12 \n" +
	"\vrequirement\x18\x04 \x01(\tR\vrequirement\x12\x1f\n" +
	"\vworker_node\x18\x05 \x01(\tR\n" +
	"workerNode\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x12\x1f\n" +
	"\vsubmit_time\x18\b \x01(\x03R\n" +
	"submitTime\x12\x19\n" +
	"\bgroup_id\x18\t \x01(\tR\agroupId\"\xe9\x01\n" +
	"\x13ReportResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vworker_node\x18\x02 \x01(\tR\n" +
	"workerNode\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x18\n" +
	"\aattempt\x18\b \x01(\x03R\aattempt\":\n" +
	"\x14ReportResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xab\x06\n" +
	"\x10SchedulerService\x128\n" +
	"\tSubmitJob\x12\x14.v1.SubmitJobRequest\x1a\x15.v1.SubmitJobResponse\x12Y\n" +
	"\x14SubmitDistributedJob\x12\x1f.v1.SubmitDistributedJobRequest\x1a .v1.SubmitDistributedJobResponse\x128\n" +
	"\tCancelJob\x12\x14.v1.CancelJobRequest\x1a\x15.v1.CancelJobResponse\x12A\n" +
	"\fGetJobStatus\x12\x17.v1.GetJobStatusRequest\x1a\x18.v1.GetJobStatusResponse\x124\n" +
	"\n" +
	"StreamLogs\x12\x14.v1.LogStreamRequest\x1a\x0e.v1.LogMessage0\x01\x12A\n" +
	"\fWorkerStatus\x12\x17.v1.WorkerStatusRequest\x1a\x18.v1.WorkerStatusResponse\x125\n" +
	"\bListJobs\x12\x13.v1.ListJobsRequest\x1a\x14.v1.ListJobsResponse\x12A\n" +
	"\fReportResult\x12\x17.v1.ReportResultRequest\x1a\x18.v1.ReportResultResponse\x12D\n" +
	"\rClusterStatus\x12\x18.v1.ClusterStatusRequest\x1a\x19.v1.ClusterStatusResponse\x12;\n" +
	"\n" +
	"CordonNode\x12\x15.v1.CordonNodeRequest\x1a\x16.v1.CordonNodeResponse\x12M\n" +
	"\x10AcknowledgeStart\x12\x1b.v1.AcknowledgeStartRequest\x1a\x1c.v1.AcknowledgeStartResponse\x12@\n" +
	"\rWatchDispatch\x12\x18.v1.WatchDispatchRequest\x1a\x13.v1.DispatchMessage0\x01B Z\x1egithub.com/deziss/tasch/api/v1b\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_scheduler_proto_goTypes = []any{
	(*ClusterStatusRequest)(nil),         // 0: v1.ClusterStatusRequest
	(*ClusterStatusResponse)(nil),        // 1: v1.ClusterStatusResponse
	(*ClusterMember)(nil),                // 2: v1.ClusterMember
	(*CordonNodeRequest)(nil),            // 3: v1.CordonNodeRequest
	(*CordonNodeResponse)(nil),           // 4: v1.CordonNodeResponse
	(*AcknowledgeStartRequest)(nil),      // 5: v1.AcknowledgeStartRequest
	(*AcknowledgeStartResponse)(nil),     // 6: v1.AcknowledgeStartResponse
	(*WatchDispatchRequest)(nil),         // 7: v1.WatchDispatchRequest
	(*RunningJob)(nil),                   // 8: v1.RunningJob
	(*DispatchMessage)(nil),              // 9: v1.DispatchMessage
	(*SubmitJobRequest)(nil),             // 10: v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),            // 11: v1.SubmitJobResponse
	(*SubmitDistributedJobRequest)(nil),  // 12: v1.SubmitDistributedJobRequest
	(*SubmitDistributedJobResponse)(nil), // 13: v1.SubmitDistributedJobResponse
	(*CancelJobRequest)(nil),             // 14: v1.CancelJobRequest
	(*CancelJobResponse)(nil),            // 15: v1.CancelJobResponse
	(*GetJobStatusRequest)(nil),          // 16: v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),         // 17: v1.GetJobStatusResponse
	(*LogStreamRequest)(nil),             // 18: v1.LogStreamRequest
	(*LogMessage)(nil),                   // 19: v1.LogMessage
	(*WorkerStatusRequest)(nil),          // 20: v1.WorkerStatusRequest
	(*WorkerStatusResponse)(nil),         // 21: v1.WorkerStatusResponse
	(*NodeSchedulingState)(nil),          // 22: v1.NodeSchedulingState
	(*ListJobsRequest)(nil),              // 23: v1.ListJobsRequest
	(*ListJobsResponse)(nil),             // 24: v1.ListJobsResponse
	(*JobInfo)(nil),                      // 25: v1.JobInfo
	(*ReportResultRequest)(nil),          // 26: v1.ReportResultRequest
	(*ReportResultResponse)(nil),         // 27: v1.ReportResultResponse
	nil,                                  // 28: v1.DispatchMessage.EnvVarsEntry
	nil,                                  // 29: v1.SubmitJobRequest.EnvVarsEntry
	nil,                                  // 30: v1.SubmitDistributedJobRequest.EnvVarsEntry
	nil,                                  // 31: v1.WorkerStatusResponse.WorkerNodesEntry
	nil,                                  // 32: v1.WorkerStatusResponse.NodeStateEntry
}
var file_scheduler_proto_depIdxs = []int32{
	2,  // 0: v1.ClusterStatusResponse.members:type_name -> v1.ClusterMember
	8,  // 1: v1.WatchDispatchRequest.running_jobs:type_name -> v1.RunningJob
	28, // 2: v1.DispatchMessage.env_vars:type_name -> v1.DispatchMessage.EnvVarsEntry
	29, // 3: v1.SubmitJobRequest.env_vars:type_name -> v1.SubmitJobRequest.EnvVarsEntry
	30, // 4: v1.SubmitDistributedJobRequest.env_vars:type_name -> v1.SubmitDistributedJobRequest.EnvVarsEntry
	31, // 5: v1.WorkerStatusResponse.worker_nodes:type_name -> v1.WorkerStatusResponse.WorkerNodesEntry
	32, // 6: v1.WorkerStatusResponse.node_state:type_name -> v1.WorkerStatusResponse.NodeStateEntry
	25, // 7: v1.ListJobsResponse.jobs:type_name -> v1.JobInfo
	22, // 8: v1.WorkerStatusResponse.NodeStateEntry.value:type_name -> v1.NodeSchedulingState
	10, // 9: v1.SchedulerService.SubmitJob:input_type -> v1.SubmitJobRequest
	12, // 10: v1.SchedulerService.SubmitDistributedJob:input_type -> v1.SubmitDistributedJobRequest
	14, // 11: v1.SchedulerService.CancelJob:input_type -> v1.CancelJobRequest
	16, // 12: v1.SchedulerService.GetJobStatus:input_type -> v1.GetJobStatusRequest
	18, // 13: v1.SchedulerService.StreamLogs:input_type -> v1.LogStreamRequest
	20, // 14: v1.SchedulerService.WorkerStatus:input_type -> v1.WorkerStatusRequest
	23, // 15: v1.SchedulerService.ListJobs:input_type -> v1.ListJobsRequest
	26, // 16: v1.SchedulerService.ReportResult:input_type -> v1.ReportResultRequest
	0,  // 17: v1.SchedulerService.ClusterStatus:input_type -> v1.ClusterStatusRequest
	3,  // 18: v1.SchedulerService.CordonNode:input_type -> v1.CordonNodeRequest
	5,  // 19: v1.SchedulerService.AcknowledgeStart:input_type -> v1.AcknowledgeStartRequest
	7,  // 20: v1.SchedulerService.WatchDispatch:input_type -> v1.WatchDispatchRequest
	11, // 21: v1.SchedulerService.SubmitJob:output_type -> v1.SubmitJobResponse
	13, // 22: v1.SchedulerService.SubmitDistributedJob:output_type -> v1.SubmitDistributedJobResponse
	15, // 23: v1.SchedulerService.CancelJob:output_type -> v1.CancelJobResponse
	17, // 24: v1.SchedulerService.GetJobStatus:output_type -> v1.GetJobStatusResponse
	19, // 25: v1.SchedulerService.StreamLogs:output_type -> v1.LogMessage
	21, // 26: v1.SchedulerService.WorkerStatus:output_type -> v1.WorkerStatusResponse
	24, // 27: v1.SchedulerService.ListJobs:output_type -> v1.ListJobsResponse
	27, // 28: v1.SchedulerService.ReportResult:output_type -> v1.ReportResultResponse
	1,  // 29: v1.SchedulerService.ClusterStatus:output_type -> v1.ClusterStatusResponse
	4,  // 30: v1.SchedulerService.CordonNode:output_type -> v1.CordonNodeResponse
	6,  // 31: v1.SchedulerService.AcknowledgeStart:output_type -> v1.AcknowledgeStartResponse
	9,  // 32: v1.SchedulerService.WatchDispatch:output_type -> v1.DispatchMessage
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
