// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scheduler.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcknowledgeStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerNode    string                 `protobuf:"bytes,2,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Attempt       int64                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeStartRequest) Reset() {
	*x = AcknowledgeStartRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeStartRequest) ProtoMessage() {}

func (x *AcknowledgeStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeStartRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeStartRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *AcknowledgeStartRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AcknowledgeStartRequest) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *AcknowledgeStartRequest) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type AcknowledgeStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeStartResponse) Reset() {
	*x = AcknowledgeStartResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeStartResponse) ProtoMessage() {}

func (x *AcknowledgeStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeStartResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeStartResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *AcknowledgeStartResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type WatchDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDispatchRequest) Reset() {
	*x = WatchDispatchRequest{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDispatchRequest) ProtoMessage() {}

func (x *WatchDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDispatchRequest.ProtoReflect.Descriptor instead.
func (*WatchDispatchRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *WatchDispatchRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type DispatchMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	WalltimeSeconds int32                  `protobuf:"varint,3,opt,name=walltime_seconds,json=walltimeSeconds,proto3" json:"walltime_seconds,omitempty"`
	Action          string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // "execute" or "cancel"
	EnvVars         map[string]string      `protobuf:"bytes,5,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Attempt         int64                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"` // Fencing token, echoed back in ReportResult
	// Resource reservations, so the worker can enforce them rather than leaving them as
	// bookkeeping on the master. A job that reserved one core could previously consume the whole
	// machine, because nothing on the worker ever applied a limit.
	CpusRequired     int32 `protobuf:"varint,7,opt,name=cpus_required,json=cpusRequired,proto3" json:"cpus_required,omitempty"`
	MemoryRequiredMb int32 `protobuf:"varint,8,opt,name=memory_required_mb,json=memoryRequiredMb,proto3" json:"memory_required_mb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DispatchMessage) Reset() {
	*x = DispatchMessage{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchMessage) ProtoMessage() {}

func (x *DispatchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchMessage.ProtoReflect.Descriptor instead.
func (*DispatchMessage) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchMessage) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchMessage) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DispatchMessage) GetWalltimeSeconds() int32 {
	if x != nil {
		return x.WalltimeSeconds
	}
	return 0
}

func (x *DispatchMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DispatchMessage) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *DispatchMessage) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DispatchMessage) GetCpusRequired() int32 {
	if x != nil {
		return x.CpusRequired
	}
	return 0
}

func (x *DispatchMessage) GetMemoryRequiredMb() int32 {
	if x != nil {
		return x.MemoryRequiredMb
	}
	return 0
}

type SubmitJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CelRequirement  string                 `protobuf:"bytes,1,opt,name=cel_requirement,json=celRequirement,proto3" json:"cel_requirement,omitempty"`
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Priority        int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                                                                       // Lower = higher priority (default: 10)
	User            string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                                                                                // For fairshare tracking
	WalltimeSeconds int32                  `protobuf:"varint,5,opt,name=walltime_seconds,json=walltimeSeconds,proto3" json:"walltime_seconds,omitempty"`                                                  // Max execution time (0 = no limit)
	GpusRequired    int32                  `protobuf:"varint,6,opt,name=gpus_required,json=gpusRequired,proto3" json:"gpus_required,omitempty"`                                                           // Number of GPUs needed (0 = none)
	EnvVars         map[string]string      `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom environment variables
	// Explicit resource reservations. Distinct from cel_requirement, which filters which nodes
	// are eligible: "ad.cpu_cores >= 4" asks for a node with at least 4 cores, it does not
	// reserve 4 of them. These were previously scraped out of the CEL string with a regex, so
	// any expression the regex did not literally match reserved nothing and the node was freely
	// oversubscribed. 0 falls back to that regex for backward compatibility.
	CpusRequired     int32 `protobuf:"varint,8,opt,name=cpus_required,json=cpusRequired,proto3" json:"cpus_required,omitempty"`               // CPU cores to reserve (0 = infer from cel_requirement)
	MemoryRequiredMb int32 `protobuf:"varint,9,opt,name=memory_required_mb,json=memoryRequiredMb,proto3" json:"memory_required_mb,omitempty"` // Memory to reserve in MB (0 = infer)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitJobRequest) GetCelRequirement() string {
	if x != nil {
		return x.CelRequirement
	}
	return ""
}

func (x *SubmitJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SubmitJobRequest) GetWalltimeSeconds() int32 {
	if x != nil {
		return x.WalltimeSeconds
	}
	return 0
}

func (x *SubmitJobRequest) GetGpusRequired() int32 {
	if x != nil {
		return x.GpusRequired
	}
	return 0
}

func (x *SubmitJobRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *SubmitJobRequest) GetCpusRequired() int32 {
	if x != nil {
		return x.CpusRequired
	}
	return 0
}

func (x *SubmitJobRequest) GetMemoryRequiredMb() int32 {
	if x != nil {
		return x.MemoryRequiredMb
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubmitDistributedJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CelRequirement  string                 `protobuf:"bytes,1,opt,name=cel_requirement,json=celRequirement,proto3" json:"cel_requirement,omitempty"` // Must match on ALL allocated nodes
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                     // Command template (same on all nodes)
	NumNodes        int32                  `protobuf:"varint,3,opt,name=num_nodes,json=numNodes,proto3" json:"num_nodes,omitempty"`                  // How many nodes to allocate
	GpusPerNode     int32                  `protobuf:"varint,4,opt,name=gpus_per_node,json=gpusPerNode,proto3" json:"gpus_per_node,omitempty"`       // GPUs per node
	Priority        int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	User            string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	WalltimeSeconds int32                  `protobuf:"varint,7,opt,name=walltime_seconds,json=walltimeSeconds,proto3" json:"walltime_seconds,omitempty"`
	MasterPort      int32                  `protobuf:"varint,8,opt,name=master_port,json=masterPort,proto3" json:"master_port,omitempty"`                                                                 // DDP coordination port (default: 29500)
	EnvVars         map[string]string      `protobuf:"bytes,9,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional env vars for all ranks
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitDistributedJobRequest) Reset() {
	*x = SubmitDistributedJobRequest{}
	mi := &file_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDistributedJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDistributedJobRequest) ProtoMessage() {}

func (x *SubmitDistributedJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDistributedJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitDistributedJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitDistributedJobRequest) GetCelRequirement() string {
	if x != nil {
		return x.CelRequirement
	}
	return ""
}

func (x *SubmitDistributedJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SubmitDistributedJobRequest) GetNumNodes() int32 {
	if x != nil {
		return x.NumNodes
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetGpusPerNode() int32 {
	if x != nil {
		return x.GpusPerNode
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SubmitDistributedJobRequest) GetWalltimeSeconds() int32 {
	if x != nil {
		return x.WalltimeSeconds
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetMasterPort() int32 {
	if x != nil {
		return x.MasterPort
	}
	return 0
}

func (x *SubmitDistributedJobRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type SubmitDistributedJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	JobIds        []string               `protobuf:"bytes,2,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDistributedJobResponse) Reset() {
	*x = SubmitDistributedJobResponse{}
	mi := &file_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDistributedJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDistributedJobResponse) ProtoMessage() {}

func (x *SubmitDistributedJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDistributedJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitDistributedJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitDistributedJobResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SubmitDistributedJobResponse) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

func (x *SubmitDistributedJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *CancelJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // QUEUED, RUNNING, COMPLETED, FAILED, CANCELLED
	WorkerNode    string                 `protobuf:"bytes,3,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	SubmitTime    int64                  `protobuf:"varint,7,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	StartTime     int64                  `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	GroupId       string                 `protobuf:"bytes,10,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // Empty if not part of a distributed job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetJobStatusResponse) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *GetJobStatusResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetJobStatusResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GetJobStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetJobStatusResponse) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *GetJobStatusResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetJobStatusResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetJobStatusResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type LogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	mi := &file_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *LogStreamRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *LogMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogMessage) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WorkerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatusRequest) Reset() {
	*x = WorkerStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusRequest) ProtoMessage() {}

func (x *WorkerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusRequest.ProtoReflect.Descriptor instead.
func (*WorkerStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{14}
}

type WorkerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerNodes   map[string]string      `protobuf:"bytes,1,rep,name=worker_nodes,json=workerNodes,proto3" json:"worker_nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatusResponse) Reset() {
	*x = WorkerStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusResponse) ProtoMessage() {}

func (x *WorkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *WorkerStatusResponse) GetWorkerNodes() map[string]string {
	if x != nil {
		return x.WorkerNodes
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateFilter   string                 `protobuf:"bytes,1,opt,name=state_filter,json=stateFilter,proto3" json:"state_filter,omitempty"` // Optional: filter by state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *ListJobsRequest) GetStateFilter() string {
	if x != nil {
		return x.StateFilter
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Requirement   string                 `protobuf:"bytes,4,opt,name=requirement,proto3" json:"requirement,omitempty"`
	WorkerNode    string                 `protobuf:"bytes,5,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	User          string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	SubmitTime    int64                  `protobuf:"varint,8,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	GroupId       string                 `protobuf:"bytes,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{18}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobInfo) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *JobInfo) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *JobInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *JobInfo) GetSubmitTime() int64 {
	if x != nil {
		return x.SubmitTime
	}
	return 0
}

func (x *JobInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ReportResultRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerNode string                 `protobuf:"bytes,2,opt,name=worker_node,json=workerNode,proto3" json:"worker_node,omitempty"`
	Success    bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output     string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error      string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	StartTime  int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime    int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Dispatch attempt this result belongs to, echoed back from the dispatch payload. The master
	// discards results from a stale attempt: without it, a late report from a previously
	// dispatched worker released the allocation belonging to whichever node is running the job
	// now, and no result could be told apart from a duplicate.
	Attempt       int64 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *ReportResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportResultRequest) GetWorkerNode() string {
	if x != nil {
		return x.WorkerNode
	}
	return ""
}

func (x *ReportResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ReportResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportResultRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ReportResultRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ReportResultRequest) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *ReportResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\x02v1\"k\n" +
	"\x17AcknowledgeStartRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vworker_node\x18\x02 \x01(\tR\n" +
	"workerNode\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x03R\aattempt\">\n" +
	"\x18AcknowledgeStartResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"3\n" +
	"\x14WatchDispatchRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"\xeb\x02\n" +
	"\x0fDispatchMessage\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12)\n" +
	"\x10walltime_seconds\x18\x03 \x01(\x05R\x0fwalltimeSeconds\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12;\n" +
	"\benv_vars\x18\x05 \x03(\v2 .v1.DispatchMessage.EnvVarsEntryR\aenvVars\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x03R\aattempt\x12#\n" +
	"\rcpus_required\x18\a \x01(\x05R\fcpusRequired\x12,\n" +
	"\x12memory_required_mb\x18\b \x01(\x05R\x10memoryRequiredMb\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x03\n" +
	"\x10SubmitJobRequest\x12'\n" +
	"\x0fcel_requirement\x18\x01 \x01(\tR\x0ecelRequirement\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12)\n" +
	"\x10walltime_seconds\x18\x05 \x01(\x05R\x0fwalltimeSeconds\x12#\n" +
	"\rgpus_required\x18\x06 \x01(\x05R\fgpusRequired\x12<\n" +
	"\benv_vars\x18\a \x03(\v2!.v1.SubmitJobRequest.EnvVarsEntryR\aenvVars\x12#\n" +
	"\rcpus_required\x18\b \x01(\x05R\fcpusRequired\x12,\n" +
	"\x12memory_required_mb\x18\t \x01(\x05R\x10memoryRequiredMb\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa2\x03\n" +
	"\x1bSubmitDistributedJobRequest\x12'\n" +
	"\x0fcel_requirement\x18\x01 \x01(\tR\x0ecelRequirement\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1b\n" +
	"\tnum_nodes\x18\x03 \x01(\x05R\bnumNodes\x12\"\n" +
	"\rgpus_per_node\x18\x04 \x01(\x05R\vgpusPerNode\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12)\n" +
	"\x10walltime_seconds\x18\a \x01(\x05R\x0fwalltimeSeconds\x12\x1f\n" +
	"\vmaster_port\x18\b \x01(\x05R\n" +
	"masterPort\x12G\n" +
	"\benv_vars\x18\t \x03(\v2,.v1.SubmitDistributedJobRequest.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x1cSubmitDistributedJobResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\ajob_ids\x18\x02 \x03(\tR\x06jobIds\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\\\n" +
	"\x11CancelJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xa2\x02\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vworker_node\x18\x03 \x01(\tR\n" +
	"workerNode\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vsubmit_time\x18\a \x01(\x03R\n" +
	"submitTime\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\x03R\aendTime\x12\x19\n" +
	"\bgroup_id\x18\n" +
	" \x01(\tR\agroupId\")\n" +
	"\x10LogStreamRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"q\n" +
	"\n" +
	"LogMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\"\x15\n" +
	"\x13WorkerStatusRequest\"\xa4\x01\n" +
	"\x14WorkerStatusResponse\x12L\n" +
	"\fworker_nodes\x18\x01 \x03(\v2).v1.WorkerStatusResponse.WorkerNodesEntryR\vworkerNodes\x1a>\n" +
	"\x10WorkerNodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x0fListJobsRequest\x12!\n" +
	"\fstate_filter\x18\x01 \x01(\tR\vstateFilter\"3\n" +
	"\x10ListJobsResponse\x12\x1f\n" +
	"\x04jobs\x18\x01 \x03(\v2\v.v1.JobInfoR\x04jobs\"\xff\x01\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12 \n" +
	"\vrequirement\x18\x04 \x01(\tR\vrequirement\x12\x1f\n" +
	"\vworker_node\x18\x05 \x01(\tR\n" +
	"workerNode\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x12\x1f\n" +
	"\vsubmit_time\x18\b \x01(\x03R\n" +
	"submitTime\x12\x19\n" +
	"\bgroup_id\x18\t \x01(\tR\agroupId\"\xe9\x01\n" +
	"\x13ReportResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vworker_node\x18\x02 \x01(\tR\n" +
	"workerNode\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x18\n" +
	"\aattempt\x18\b \x01(\x03R\aattempt\":\n" +
	"\x14ReportResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xa8\x05\n" +
	"\x10SchedulerService\x128\n" +
	"\tSubmitJob\x12\x14.v1.SubmitJobRequest\x1a\x15.v1.SubmitJobResponse\x12Y\n" +
	"\x14SubmitDistributedJob\x12\x1f.v1.SubmitDistributedJobRequest\x1a .v1.SubmitDistributedJobResponse\x128\n" +
	"\tCancelJob\x12\x14.v1.CancelJobRequest\x1a\x15.v1.CancelJobResponse\x12A\n" +
	"\fGetJobStatus\x12\x17.v1.GetJobStatusRequest\x1a\x18.v1.GetJobStatusResponse\x124\n" +
	"\n" +
	"StreamLogs\x12\x14.v1.LogStreamRequest\x1a\x0e.v1.LogMessage0\x01\x12A\n" +
	"\fWorkerStatus\x12\x17.v1.WorkerStatusRequest\x1a\x18.v1.WorkerStatusResponse\x125\n" +
	"\bListJobs\x12\x13.v1.ListJobsRequest\x1a\x14.v1.ListJobsResponse\x12A\n" +
	"\fReportResult\x12\x17.v1.ReportResultRequest\x1a\x18.v1.ReportResultResponse\x12M\n" +
	"\x10AcknowledgeStart\x12\x1b.v1.AcknowledgeStartRequest\x1a\x1c.v1.AcknowledgeStartResponse\x12@\n" +
	"\rWatchDispatch\x12\x18.v1.WatchDispatchRequest\x1a\x13.v1.DispatchMessage0\x01B Z\x1egithub.com/deziss/tasch/api/v1b\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_scheduler_proto_goTypes = []any{
	(*AcknowledgeStartRequest)(nil),      // 0: v1.AcknowledgeStartRequest
	(*AcknowledgeStartResponse)(nil),     // 1: v1.AcknowledgeStartResponse
	(*WatchDispatchRequest)(nil),         // 2: v1.WatchDispatchRequest
	(*DispatchMessage)(nil),              // 3: v1.DispatchMessage
	(*SubmitJobRequest)(nil),             // 4: v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),            // 5: v1.SubmitJobResponse
	(*SubmitDistributedJobRequest)(nil),  // 6: v1.SubmitDistributedJobRequest
	(*SubmitDistributedJobResponse)(nil), // 7: v1.SubmitDistributedJobResponse
	(*CancelJobRequest)(nil),             // 8: v1.CancelJobRequest
	(*CancelJobResponse)(nil),            // 9: v1.CancelJobResponse
	(*GetJobStatusRequest)(nil),          // 10: v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),         // 11: v1.GetJobStatusResponse
	(*LogStreamRequest)(nil),             // 12: v1.LogStreamRequest
	(*LogMessage)(nil),                   // 13: v1.LogMessage
	(*WorkerStatusRequest)(nil),          // 14: v1.WorkerStatusRequest
	(*WorkerStatusResponse)(nil),         // 15: v1.WorkerStatusResponse
	(*ListJobsRequest)(nil),              // 16: v1.ListJobsRequest
	(*ListJobsResponse)(nil),             // 17: v1.ListJobsResponse
	(*JobInfo)(nil),                      // 18: v1.JobInfo
	(*ReportResultRequest)(nil),          // 19: v1.ReportResultRequest
	(*ReportResultResponse)(nil),         // 20: v1.ReportResultResponse
	nil,                                  // 21: v1.DispatchMessage.EnvVarsEntry
	nil,                                  // 22: v1.SubmitJobRequest.EnvVarsEntry
	nil,                                  // 23: v1.SubmitDistributedJobRequest.EnvVarsEntry
	nil,                                  // 24: v1.WorkerStatusResponse.WorkerNodesEntry
}
var file_scheduler_proto_depIdxs = []int32{
	21, // 0: v1.DispatchMessage.env_vars:type_name -> v1.DispatchMessage.EnvVarsEntry
	22, // 1: v1.SubmitJobRequest.env_vars:type_name -> v1.SubmitJobRequest.EnvVarsEntry
	23, // 2: v1.SubmitDistributedJobRequest.env_vars:type_name -> v1.SubmitDistributedJobRequest.EnvVarsEntry
	24, // 3: v1.WorkerStatusResponse.worker_nodes:type_name -> v1.WorkerStatusResponse.WorkerNodesEntry
	18, // 4: v1.ListJobsResponse.jobs:type_name -> v1.JobInfo
	4,  // 5: v1.SchedulerService.SubmitJob:input_type -> v1.SubmitJobRequest
	6,  // 6: v1.SchedulerService.SubmitDistributedJob:input_type -> v1.SubmitDistributedJobRequest
	8,  // 7: v1.SchedulerService.CancelJob:input_type -> v1.CancelJobRequest
	10, // 8: v1.SchedulerService.GetJobStatus:input_type -> v1.GetJobStatusRequest
	12, // 9: v1.SchedulerService.StreamLogs:input_type -> v1.LogStreamRequest
	14, // 10: v1.SchedulerService.WorkerStatus:input_type -> v1.WorkerStatusRequest
	16, // 11: v1.SchedulerService.ListJobs:input_type -> v1.ListJobsRequest
	19, // 12: v1.SchedulerService.ReportResult:input_type -> v1.ReportResultRequest
	0,  // 13: v1.SchedulerService.AcknowledgeStart:input_type -> v1.AcknowledgeStartRequest
	2,  // 14: v1.SchedulerService.WatchDispatch:input_type -> v1.WatchDispatchRequest
	5,  // 15: v1.SchedulerService.SubmitJob:output_type -> v1.SubmitJobResponse
	7,  // 16: v1.SchedulerService.SubmitDistributedJob:output_type -> v1.SubmitDistributedJobResponse
	9,  // 17: v1.SchedulerService.CancelJob:output_type -> v1.CancelJobResponse
	11, // 18: v1.SchedulerService.GetJobStatus:output_type -> v1.GetJobStatusResponse
	13, // 19: v1.SchedulerService.StreamLogs:output_type -> v1.LogMessage
	15, // 20: v1.SchedulerService.WorkerStatus:output_type -> v1.WorkerStatusResponse
	17, // 21: v1.SchedulerService.ListJobs:output_type -> v1.ListJobsResponse
	20, // 22: v1.SchedulerService.ReportResult:output_type -> v1.ReportResultResponse
	1,  // 23: v1.SchedulerService.AcknowledgeStart:output_type -> v1.AcknowledgeStartResponse
	3,  // 24: v1.SchedulerService.WatchDispatch:output_type -> v1.DispatchMessage
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
