// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: scheduler.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/deziss/tasch/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SchedulerServiceName is the fully-qualified name of the SchedulerService service.
	SchedulerServiceName = "v1.SchedulerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SchedulerServiceSubmitJobProcedure is the fully-qualified name of the SchedulerService's
	// SubmitJob RPC.
	SchedulerServiceSubmitJobProcedure = "/v1.SchedulerService/SubmitJob"
	// SchedulerServiceSubmitDistributedJobProcedure is the fully-qualified name of the
	// SchedulerService's SubmitDistributedJob RPC.
	SchedulerServiceSubmitDistributedJobProcedure = "/v1.SchedulerService/SubmitDistributedJob"
	// SchedulerServiceCancelJobProcedure is the fully-qualified name of the SchedulerService's
	// CancelJob RPC.
	SchedulerServiceCancelJobProcedure = "/v1.SchedulerService/CancelJob"
	// SchedulerServiceGetJobStatusProcedure is the fully-qualified name of the SchedulerService's
	// GetJobStatus RPC.
	SchedulerServiceGetJobStatusProcedure = "/v1.SchedulerService/GetJobStatus"
	// SchedulerServiceStreamLogsProcedure is the fully-qualified name of the SchedulerService's
	// StreamLogs RPC.
	SchedulerServiceStreamLogsProcedure = "/v1.SchedulerService/StreamLogs"
	// SchedulerServiceWorkerStatusProcedure is the fully-qualified name of the SchedulerService's
	// WorkerStatus RPC.
	SchedulerServiceWorkerStatusProcedure = "/v1.SchedulerService/WorkerStatus"
	// SchedulerServiceListJobsProcedure is the fully-qualified name of the SchedulerService's ListJobs
	// RPC.
	SchedulerServiceListJobsProcedure = "/v1.SchedulerService/ListJobs"
	// SchedulerServiceReportResultProcedure is the fully-qualified name of the SchedulerService's
	// ReportResult RPC.
	SchedulerServiceReportResultProcedure = "/v1.SchedulerService/ReportResult"
	// SchedulerServiceClusterStatusProcedure is the fully-qualified name of the SchedulerService's
	// ClusterStatus RPC.
	SchedulerServiceClusterStatusProcedure = "/v1.SchedulerService/ClusterStatus"
	// SchedulerServiceCordonNodeProcedure is the fully-qualified name of the SchedulerService's
	// CordonNode RPC.
	SchedulerServiceCordonNodeProcedure = "/v1.SchedulerService/CordonNode"
	// SchedulerServiceCreateReservationProcedure is the fully-qualified name of the SchedulerService's
	// CreateReservation RPC.
	SchedulerServiceCreateReservationProcedure = "/v1.SchedulerService/CreateReservation"
	// SchedulerServiceDeleteReservationProcedure is the fully-qualified name of the SchedulerService's
	// DeleteReservation RPC.
	SchedulerServiceDeleteReservationProcedure = "/v1.SchedulerService/DeleteReservation"
	// SchedulerServiceListReservationsProcedure is the fully-qualified name of the SchedulerService's
	// ListReservations RPC.
	SchedulerServiceListReservationsProcedure = "/v1.SchedulerService/ListReservations"
	// SchedulerServiceAcknowledgeStartProcedure is the fully-qualified name of the SchedulerService's
	// AcknowledgeStart RPC.
	SchedulerServiceAcknowledgeStartProcedure = "/v1.SchedulerService/AcknowledgeStart"
	// SchedulerServiceWatchDispatchProcedure is the fully-qualified name of the SchedulerService's
	// WatchDispatch RPC.
	SchedulerServiceWatchDispatchProcedure = "/v1.SchedulerService/WatchDispatch"
)

// SchedulerServiceClient is a client for the v1.SchedulerService service.
type SchedulerServiceClient interface {
	// Submit a job with a CEL requirement constraint
	SubmitJob(context.Context, *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.SubmitJobResponse], error)
	// Submit a distributed training job across multiple nodes
	SubmitDistributedJob(context.Context, *connect.Request[v1.SubmitDistributedJobRequest]) (*connect.Response[v1.SubmitDistributedJobResponse], error)
	// Cancel a queued or running job
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
	// Get the status and result of a specific job
	GetJobStatus(context.Context, *connect.Request[v1.GetJobStatusRequest]) (*connect.Response[v1.GetJobStatusResponse], error)
	// Stream execution logs back from a running or completed job
	StreamLogs(context.Context, *connect.Request[v1.LogStreamRequest]) (*connect.ServerStreamForClient[v1.LogMessage], error)
	// Retrieve the global queued tasks and active workers states
	WorkerStatus(context.Context, *connect.Request[v1.WorkerStatusRequest]) (*connect.Response[v1.WorkerStatusResponse], error)
	// List all jobs in the queue with their states
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// Worker reports job completion/failure back to master
	ReportResult(context.Context, *connect.Request[v1.ReportResultRequest]) (*connect.Response[v1.ReportResultResponse], error)
	// Report this master's role in the replicated cluster.
	//
	// Clients need it to find the master currently accepting writes: every master answers reads,
	// but only the leader accepts changes, and which one that is moves on failover.
	ClusterStatus(context.Context, *connect.Request[v1.ClusterStatusRequest]) (*connect.Response[v1.ClusterStatusResponse], error)
	// Take a node out of, or back into, scheduling rotation.
	//
	// There was no way to stop a node receiving work for maintenance: an operator's only options
	// were to kill the worker, which fails every job running on it, or to wait. Cordoning stops
	// new dispatches while letting running jobs finish; draining additionally cancels them.
	CordonNode(context.Context, *connect.Request[v1.CordonNodeRequest]) (*connect.Response[v1.CordonNodeResponse], error)
	// Reservations. A cordon stops a node taking work now and stays until someone lifts it; a
	// reservation says when the window is, so the scheduler drains the node on its own.
	CreateReservation(context.Context, *connect.Request[v1.CreateReservationRequest]) (*connect.Response[v1.CreateReservationResponse], error)
	DeleteReservation(context.Context, *connect.Request[v1.DeleteReservationRequest]) (*connect.Response[v1.DeleteReservationResponse], error)
	ListReservations(context.Context, *connect.Request[v1.ListReservationsRequest]) (*connect.Response[v1.ListReservationsResponse], error)
	// Worker confirms it has started a job.
	//
	// This replaces an unauthenticated HTTP POST to /acknowledge_start on the metrics port. That
	// endpoint mutated scheduler state with no authentication, so a caller could forge
	// acknowledgements for guessed job IDs and disarm the safety net that re-queues a dispatch
	// nothing picked up. It also required the worker to guess the master's metrics port from its
	// own config, so the handshake silently failed whenever the two differed.
	AcknowledgeStart(context.Context, *connect.Request[v1.AcknowledgeStartRequest]) (*connect.Response[v1.AcknowledgeStartResponse], error)
	// Worker subscribes to the dispatches addressed to it.
	//
	// This replaces the ZeroMQ PUB/SUB bus, on which the master broadcast every job's command
	// and environment variables in cleartext to every subscriber, with per-node targeting
	// enforced only by the receiving worker. Anything that could reach the bus port could read
	// every credential the cluster dispatched. This stream carries only the calling node's work
	// and rides the same authenticated, optionally TLS-protected connection as everything else.
	WatchDispatch(context.Context, *connect.Request[v1.WatchDispatchRequest]) (*connect.ServerStreamForClient[v1.DispatchMessage], error)
}

// NewSchedulerServiceClient constructs a client for the v1.SchedulerService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSchedulerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SchedulerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	schedulerServiceMethods := v1.File_scheduler_proto.Services().ByName("SchedulerService").Methods()
	return &schedulerServiceClient{
		submitJob: connect.NewClient[v1.SubmitJobRequest, v1.SubmitJobResponse](
			httpClient,
			baseURL+SchedulerServiceSubmitJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("SubmitJob")),
			connect.WithClientOptions(opts...),
		),
		submitDistributedJob: connect.NewClient[v1.SubmitDistributedJobRequest, v1.SubmitDistributedJobResponse](
			httpClient,
			baseURL+SchedulerServiceSubmitDistributedJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("SubmitDistributedJob")),
			connect.WithClientOptions(opts...),
		),
		cancelJob: connect.NewClient[v1.CancelJobRequest, v1.CancelJobResponse](
			httpClient,
			baseURL+SchedulerServiceCancelJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("CancelJob")),
			connect.WithClientOptions(opts...),
		),
		getJobStatus: connect.NewClient[v1.GetJobStatusRequest, v1.GetJobStatusResponse](
			httpClient,
			baseURL+SchedulerServiceGetJobStatusProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("GetJobStatus")),
			connect.WithClientOptions(opts...),
		),
		streamLogs: connect.NewClient[v1.LogStreamRequest, v1.LogMessage](
			httpClient,
			baseURL+SchedulerServiceStreamLogsProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("StreamLogs")),
			connect.WithClientOptions(opts...),
		),
		workerStatus: connect.NewClient[v1.WorkerStatusRequest, v1.WorkerStatusResponse](
			httpClient,
			baseURL+SchedulerServiceWorkerStatusProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("WorkerStatus")),
			connect.WithClientOptions(opts...),
		),
		listJobs: connect.NewClient[v1.ListJobsRequest, v1.ListJobsResponse](
			httpClient,
			baseURL+SchedulerServiceListJobsProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
		reportResult: connect.NewClient[v1.ReportResultRequest, v1.ReportResultResponse](
			httpClient,
			baseURL+SchedulerServiceReportResultProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("ReportResult")),
			connect.WithClientOptions(opts...),
		),
		clusterStatus: connect.NewClient[v1.ClusterStatusRequest, v1.ClusterStatusResponse](
			httpClient,
			baseURL+SchedulerServiceClusterStatusProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("ClusterStatus")),
			connect.WithClientOptions(opts...),
		),
		cordonNode: connect.NewClient[v1.CordonNodeRequest, v1.CordonNodeResponse](
			httpClient,
			baseURL+SchedulerServiceCordonNodeProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("CordonNode")),
			connect.WithClientOptions(opts...),
		),
		createReservation: connect.NewClient[v1.CreateReservationRequest, v1.CreateReservationResponse](
			httpClient,
			baseURL+SchedulerServiceCreateReservationProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("CreateReservation")),
			connect.WithClientOptions(opts...),
		),
		deleteReservation: connect.NewClient[v1.DeleteReservationRequest, v1.DeleteReservationResponse](
			httpClient,
			baseURL+SchedulerServiceDeleteReservationProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("DeleteReservation")),
			connect.WithClientOptions(opts...),
		),
		listReservations: connect.NewClient[v1.ListReservationsRequest, v1.ListReservationsResponse](
			httpClient,
			baseURL+SchedulerServiceListReservationsProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("ListReservations")),
			connect.WithClientOptions(opts...),
		),
		acknowledgeStart: connect.NewClient[v1.AcknowledgeStartRequest, v1.AcknowledgeStartResponse](
			httpClient,
			baseURL+SchedulerServiceAcknowledgeStartProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("AcknowledgeStart")),
			connect.WithClientOptions(opts...),
		),
		watchDispatch: connect.NewClient[v1.WatchDispatchRequest, v1.DispatchMessage](
			httpClient,
			baseURL+SchedulerServiceWatchDispatchProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("WatchDispatch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// schedulerServiceClient implements SchedulerServiceClient.
type schedulerServiceClient struct {
	submitJob            *connect.Client[v1.SubmitJobRequest, v1.SubmitJobResponse]
	submitDistributedJob *connect.Client[v1.SubmitDistributedJobRequest, v1.SubmitDistributedJobResponse]
	cancelJob            *connect.Client[v1.CancelJobRequest, v1.CancelJobResponse]
	getJobStatus         *connect.Client[v1.GetJobStatusRequest, v1.GetJobStatusResponse]
	streamLogs           *connect.Client[v1.LogStreamRequest, v1.LogMessage]
	workerStatus         *connect.Client[v1.WorkerStatusRequest, v1.WorkerStatusResponse]
	listJobs             *connect.Client[v1.ListJobsRequest, v1.ListJobsResponse]
	reportResult         *connect.Client[v1.ReportResultRequest, v1.ReportResultResponse]
	clusterStatus        *connect.Client[v1.ClusterStatusRequest, v1.ClusterStatusResponse]
	cordonNode           *connect.Client[v1.CordonNodeRequest, v1.CordonNodeResponse]
	createReservation    *connect.Client[v1.CreateReservationRequest, v1.CreateReservationResponse]
	deleteReservation    *connect.Client[v1.DeleteReservationRequest, v1.DeleteReservationResponse]
	listReservations     *connect.Client[v1.ListReservationsRequest, v1.ListReservationsResponse]
	acknowledgeStart     *connect.Client[v1.AcknowledgeStartRequest, v1.AcknowledgeStartResponse]
	watchDispatch        *connect.Client[v1.WatchDispatchRequest, v1.DispatchMessage]
}

// SubmitJob calls v1.SchedulerService.SubmitJob.
func (c *schedulerServiceClient) SubmitJob(ctx context.Context, req *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.SubmitJobResponse], error) {
	return c.submitJob.CallUnary(ctx, req)
}

// SubmitDistributedJob calls v1.SchedulerService.SubmitDistributedJob.
func (c *schedulerServiceClient) SubmitDistributedJob(ctx context.Context, req *connect.Request[v1.SubmitDistributedJobRequest]) (*connect.Response[v1.SubmitDistributedJobResponse], error) {
	return c.submitDistributedJob.CallUnary(ctx, req)
}

// CancelJob calls v1.SchedulerService.CancelJob.
func (c *schedulerServiceClient) CancelJob(ctx context.Context, req *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return c.cancelJob.CallUnary(ctx, req)
}

// GetJobStatus calls v1.SchedulerService.GetJobStatus.
func (c *schedulerServiceClient) GetJobStatus(ctx context.Context, req *connect.Request[v1.GetJobStatusRequest]) (*connect.Response[v1.GetJobStatusResponse], error) {
	return c.getJobStatus.CallUnary(ctx, req)
}

// StreamLogs calls v1.SchedulerService.StreamLogs.
func (c *schedulerServiceClient) StreamLogs(ctx context.Context, req *connect.Request[v1.LogStreamRequest]) (*connect.ServerStreamForClient[v1.LogMessage], error) {
	return c.streamLogs.CallServerStream(ctx, req)
}

// WorkerStatus calls v1.SchedulerService.WorkerStatus.
func (c *schedulerServiceClient) WorkerStatus(ctx context.Context, req *connect.Request[v1.WorkerStatusRequest]) (*connect.Response[v1.WorkerStatusResponse], error) {
	return c.workerStatus.CallUnary(ctx, req)
}

// ListJobs calls v1.SchedulerService.ListJobs.
func (c *schedulerServiceClient) ListJobs(ctx context.Context, req *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// ReportResult calls v1.SchedulerService.ReportResult.
func (c *schedulerServiceClient) ReportResult(ctx context.Context, req *connect.Request[v1.ReportResultRequest]) (*connect.Response[v1.ReportResultResponse], error) {
	return c.reportResult.CallUnary(ctx, req)
}

// ClusterStatus calls v1.SchedulerService.ClusterStatus.
func (c *schedulerServiceClient) ClusterStatus(ctx context.Context, req *connect.Request[v1.ClusterStatusRequest]) (*connect.Response[v1.ClusterStatusResponse], error) {
	return c.clusterStatus.CallUnary(ctx, req)
}

// CordonNode calls v1.SchedulerService.CordonNode.
func (c *schedulerServiceClient) CordonNode(ctx context.Context, req *connect.Request[v1.CordonNodeRequest]) (*connect.Response[v1.CordonNodeResponse], error) {
	return c.cordonNode.CallUnary(ctx, req)
}

// CreateReservation calls v1.SchedulerService.CreateReservation.
func (c *schedulerServiceClient) CreateReservation(ctx context.Context, req *connect.Request[v1.CreateReservationRequest]) (*connect.Response[v1.CreateReservationResponse], error) {
	return c.createReservation.CallUnary(ctx, req)
}

// DeleteReservation calls v1.SchedulerService.DeleteReservation.
func (c *schedulerServiceClient) DeleteReservation(ctx context.Context, req *connect.Request[v1.DeleteReservationRequest]) (*connect.Response[v1.DeleteReservationResponse], error) {
	return c.deleteReservation.CallUnary(ctx, req)
}

// ListReservations calls v1.SchedulerService.ListReservations.
func (c *schedulerServiceClient) ListReservations(ctx context.Context, req *connect.Request[v1.ListReservationsRequest]) (*connect.Response[v1.ListReservationsResponse], error) {
	return c.listReservations.CallUnary(ctx, req)
}

// AcknowledgeStart calls v1.SchedulerService.AcknowledgeStart.
func (c *schedulerServiceClient) AcknowledgeStart(ctx context.Context, req *connect.Request[v1.AcknowledgeStartRequest]) (*connect.Response[v1.AcknowledgeStartResponse], error) {
	return c.acknowledgeStart.CallUnary(ctx, req)
}

// WatchDispatch calls v1.SchedulerService.WatchDispatch.
func (c *schedulerServiceClient) WatchDispatch(ctx context.Context, req *connect.Request[v1.WatchDispatchRequest]) (*connect.ServerStreamForClient[v1.DispatchMessage], error) {
	return c.watchDispatch.CallServerStream(ctx, req)
}

// SchedulerServiceHandler is an implementation of the v1.SchedulerService service.
type SchedulerServiceHandler interface {
	// Submit a job with a CEL requirement constraint
	SubmitJob(context.Context, *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.SubmitJobResponse], error)
	// Submit a distributed training job across multiple nodes
	SubmitDistributedJob(context.Context, *connect.Request[v1.SubmitDistributedJobRequest]) (*connect.Response[v1.SubmitDistributedJobResponse], error)
	// Cancel a queued or running job
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
	// Get the status and result of a specific job
	GetJobStatus(context.Context, *connect.Request[v1.GetJobStatusRequest]) (*connect.Response[v1.GetJobStatusResponse], error)
	// Stream execution logs back from a running or completed job
	StreamLogs(context.Context, *connect.Request[v1.LogStreamRequest], *connect.ServerStream[v1.LogMessage]) error
	// Retrieve the global queued tasks and active workers states
	WorkerStatus(context.Context, *connect.Request[v1.WorkerStatusRequest]) (*connect.Response[v1.WorkerStatusResponse], error)
	// List all jobs in the queue with their states
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// Worker reports job completion/failure back to master
	ReportResult(context.Context, *connect.Request[v1.ReportResultRequest]) (*connect.Response[v1.ReportResultResponse], error)
	// Report this master's role in the replicated cluster.
	//
	// Clients need it to find the master currently accepting writes: every master answers reads,
	// but only the leader accepts changes, and which one that is moves on failover.
	ClusterStatus(context.Context, *connect.Request[v1.ClusterStatusRequest]) (*connect.Response[v1.ClusterStatusResponse], error)
	// Take a node out of, or back into, scheduling rotation.
	//
	// There was no way to stop a node receiving work for maintenance: an operator's only options
	// were to kill the worker, which fails every job running on it, or to wait. Cordoning stops
	// new dispatches while letting running jobs finish; draining additionally cancels them.
	CordonNode(context.Context, *connect.Request[v1.CordonNodeRequest]) (*connect.Response[v1.CordonNodeResponse], error)
	// Reservations. A cordon stops a node taking work now and stays until someone lifts it; a
	// reservation says when the window is, so the scheduler drains the node on its own.
	CreateReservation(context.Context, *connect.Request[v1.CreateReservationRequest]) (*connect.Response[v1.CreateReservationResponse], error)
	DeleteReservation(context.Context, *connect.Request[v1.DeleteReservationRequest]) (*connect.Response[v1.DeleteReservationResponse], error)
	ListReservations(context.Context, *connect.Request[v1.ListReservationsRequest]) (*connect.Response[v1.ListReservationsResponse], error)
	// Worker confirms it has started a job.
	//
	// This replaces an unauthenticated HTTP POST to /acknowledge_start on the metrics port. That
	// endpoint mutated scheduler state with no authentication, so a caller could forge
	// acknowledgements for guessed job IDs and disarm the safety net that re-queues a dispatch
	// nothing picked up. It also required the worker to guess the master's metrics port from its
	// own config, so the handshake silently failed whenever the two differed.
	AcknowledgeStart(context.Context, *connect.Request[v1.AcknowledgeStartRequest]) (*connect.Response[v1.AcknowledgeStartResponse], error)
	// Worker subscribes to the dispatches addressed to it.
	//
	// This replaces the ZeroMQ PUB/SUB bus, on which the master broadcast every job's command
	// and environment variables in cleartext to every subscriber, with per-node targeting
	// enforced only by the receiving worker. Anything that could reach the bus port could read
	// every credential the cluster dispatched. This stream carries only the calling node's work
	// and rides the same authenticated, optionally TLS-protected connection as everything else.
	WatchDispatch(context.Context, *connect.Request[v1.WatchDispatchRequest], *connect.ServerStream[v1.DispatchMessage]) error
}

// NewSchedulerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSchedulerServiceHandler(svc SchedulerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	schedulerServiceMethods := v1.File_scheduler_proto.Services().ByName("SchedulerService").Methods()
	schedulerServiceSubmitJobHandler := connect.NewUnaryHandler(
		SchedulerServiceSubmitJobProcedure,
		svc.SubmitJob,
		connect.WithSchema(schedulerServiceMethods.ByName("SubmitJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceSubmitDistributedJobHandler := connect.NewUnaryHandler(
		SchedulerServiceSubmitDistributedJobProcedure,
		svc.SubmitDistributedJob,
		connect.WithSchema(schedulerServiceMethods.ByName("SubmitDistributedJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceCancelJobHandler := connect.NewUnaryHandler(
		SchedulerServiceCancelJobProcedure,
		svc.CancelJob,
		connect.WithSchema(schedulerServiceMethods.ByName("CancelJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceGetJobStatusHandler := connect.NewUnaryHandler(
		SchedulerServiceGetJobStatusProcedure,
		svc.GetJobStatus,
		connect.WithSchema(schedulerServiceMethods.ByName("GetJobStatus")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceStreamLogsHandler := connect.NewServerStreamHandler(
		SchedulerServiceStreamLogsProcedure,
		svc.StreamLogs,
		connect.WithSchema(schedulerServiceMethods.ByName("StreamLogs")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceWorkerStatusHandler := connect.NewUnaryHandler(
		SchedulerServiceWorkerStatusProcedure,
		svc.WorkerStatus,
		connect.WithSchema(schedulerServiceMethods.ByName("WorkerStatus")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceListJobsHandler := connect.NewUnaryHandler(
		SchedulerServiceListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(schedulerServiceMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceReportResultHandler := connect.NewUnaryHandler(
		SchedulerServiceReportResultProcedure,
		svc.ReportResult,
		connect.WithSchema(schedulerServiceMethods.ByName("ReportResult")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceClusterStatusHandler := connect.NewUnaryHandler(
		SchedulerServiceClusterStatusProcedure,
		svc.ClusterStatus,
		connect.WithSchema(schedulerServiceMethods.ByName("ClusterStatus")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceCordonNodeHandler := connect.NewUnaryHandler(
		SchedulerServiceCordonNodeProcedure,
		svc.CordonNode,
		connect.WithSchema(schedulerServiceMethods.ByName("CordonNode")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceCreateReservationHandler := connect.NewUnaryHandler(
		SchedulerServiceCreateReservationProcedure,
		svc.CreateReservation,
		connect.WithSchema(schedulerServiceMethods.ByName("CreateReservation")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceDeleteReservationHandler := connect.NewUnaryHandler(
		SchedulerServiceDeleteReservationProcedure,
		svc.DeleteReservation,
		connect.WithSchema(schedulerServiceMethods.ByName("DeleteReservation")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceListReservationsHandler := connect.NewUnaryHandler(
		SchedulerServiceListReservationsProcedure,
		svc.ListReservations,
		connect.WithSchema(schedulerServiceMethods.ByName("ListReservations")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceAcknowledgeStartHandler := connect.NewUnaryHandler(
		SchedulerServiceAcknowledgeStartProcedure,
		svc.AcknowledgeStart,
		connect.WithSchema(schedulerServiceMethods.ByName("AcknowledgeStart")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceWatchDispatchHandler := connect.NewServerStreamHandler(
		SchedulerServiceWatchDispatchProcedure,
		svc.WatchDispatch,
		connect.WithSchema(schedulerServiceMethods.ByName("WatchDispatch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/v1.SchedulerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SchedulerServiceSubmitJobProcedure:
			schedulerServiceSubmitJobHandler.ServeHTTP(w, r)
		case SchedulerServiceSubmitDistributedJobProcedure:
			schedulerServiceSubmitDistributedJobHandler.ServeHTTP(w, r)
		case SchedulerServiceCancelJobProcedure:
			schedulerServiceCancelJobHandler.ServeHTTP(w, r)
		case SchedulerServiceGetJobStatusProcedure:
			schedulerServiceGetJobStatusHandler.ServeHTTP(w, r)
		case SchedulerServiceStreamLogsProcedure:
			schedulerServiceStreamLogsHandler.ServeHTTP(w, r)
		case SchedulerServiceWorkerStatusProcedure:
			schedulerServiceWorkerStatusHandler.ServeHTTP(w, r)
		case SchedulerServiceListJobsProcedure:
			schedulerServiceListJobsHandler.ServeHTTP(w, r)
		case SchedulerServiceReportResultProcedure:
			schedulerServiceReportResultHandler.ServeHTTP(w, r)
		case SchedulerServiceClusterStatusProcedure:
			schedulerServiceClusterStatusHandler.ServeHTTP(w, r)
		case SchedulerServiceCordonNodeProcedure:
			schedulerServiceCordonNodeHandler.ServeHTTP(w, r)
		case SchedulerServiceCreateReservationProcedure:
			schedulerServiceCreateReservationHandler.ServeHTTP(w, r)
		case SchedulerServiceDeleteReservationProcedure:
			schedulerServiceDeleteReservationHandler.ServeHTTP(w, r)
		case SchedulerServiceListReservationsProcedure:
			schedulerServiceListReservationsHandler.ServeHTTP(w, r)
		case SchedulerServiceAcknowledgeStartProcedure:
			schedulerServiceAcknowledgeStartHandler.ServeHTTP(w, r)
		case SchedulerServiceWatchDispatchProcedure:
			schedulerServiceWatchDispatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSchedulerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSchedulerServiceHandler struct{}

func (UnimplementedSchedulerServiceHandler) SubmitJob(context.Context, *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.SubmitJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.SubmitJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) SubmitDistributedJob(context.Context, *connect.Request[v1.SubmitDistributedJobRequest]) (*connect.Response[v1.SubmitDistributedJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.SubmitDistributedJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.CancelJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) GetJobStatus(context.Context, *connect.Request[v1.GetJobStatusRequest]) (*connect.Response[v1.GetJobStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.GetJobStatus is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) StreamLogs(context.Context, *connect.Request[v1.LogStreamRequest], *connect.ServerStream[v1.LogMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.StreamLogs is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) WorkerStatus(context.Context, *connect.Request[v1.WorkerStatusRequest]) (*connect.Response[v1.WorkerStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.WorkerStatus is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.ListJobs is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) ReportResult(context.Context, *connect.Request[v1.ReportResultRequest]) (*connect.Response[v1.ReportResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.ReportResult is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) ClusterStatus(context.Context, *connect.Request[v1.ClusterStatusRequest]) (*connect.Response[v1.ClusterStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.ClusterStatus is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) CordonNode(context.Context, *connect.Request[v1.CordonNodeRequest]) (*connect.Response[v1.CordonNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.CordonNode is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) CreateReservation(context.Context, *connect.Request[v1.CreateReservationRequest]) (*connect.Response[v1.CreateReservationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.CreateReservation is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) DeleteReservation(context.Context, *connect.Request[v1.DeleteReservationRequest]) (*connect.Response[v1.DeleteReservationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.DeleteReservation is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) ListReservations(context.Context, *connect.Request[v1.ListReservationsRequest]) (*connect.Response[v1.ListReservationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.ListReservations is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) AcknowledgeStart(context.Context, *connect.Request[v1.AcknowledgeStartRequest]) (*connect.Response[v1.AcknowledgeStartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.AcknowledgeStart is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) WatchDispatch(context.Context, *connect.Request[v1.WatchDispatchRequest], *connect.ServerStream[v1.DispatchMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("v1.SchedulerService.WatchDispatch is not implemented"))
}
